// <auto-generated />
using BlazorApp1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorApp1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp1.Models.Osoba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nazwisko");

                    b.Property<int>("PlecId")
                        .HasColumnType("integer")
                        .HasColumnName("plec_id");

                    b.HasKey("Id");

                    b.HasIndex("PlecId");

                    b.ToTable("osoba", (string)null);
                });

            modelBuilder.Entity("BlazorApp1.Models.Plec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SlownikPlec");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazwa = "Mężczyzna"
                        },
                        new
                        {
                            Id = 2,
                            Nazwa = "Kobieta"
                        },
                        new
                        {
                            Id = 3,
                            Nazwa = "Inna"
                        });
                });

            modelBuilder.Entity("BlazorApp1.Models.Osoba", b =>
                {
                    b.HasOne("BlazorApp1.Models.Plec", "Plec")
                        .WithMany()
                        .HasForeignKey("PlecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plec");
                });
#pragma warning restore 612, 618
        }
    }
}
