name: CI/CD - Build, Test and Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # 3️⃣ Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # 4️⃣ Build project
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # 5️⃣ Run tests (nie przerywa workflow jeśli testy nie przejdą)
      - name: Run tests
        run: dotnet test --no-build --verbosity normal || true

      # 6️⃣ Publish project (opcjonalne, jeśli chcesz mieć out folder)
      - name: Publish project
        run: dotnet publish BlazorApp1/BlazorApp1.csproj -c Release -o out

      # 7️⃣ Install Railway CLI (bez npm)
      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      # 8️⃣ Deploy to Railway
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_KEY }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
        run: railway up
